version: "3.3"
services:
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:rw
      - mysql_db:/var/lib/mysql
    networks:
      - kong-net
      - backend_frontend

  auth:
    build: ./auth
    ports:
      - "7778:5000"
    depends_on:
      - db
    networks:
      - kong-net
      - backend_frontend

  service:
    build: ./service
    ports:
      - "7777:5000"
    depends_on:
      - db
    networks:
      - kong-net
      - backend_frontend

  admin:
    build: ./admin
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - kong-net
      - backend_frontend

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    networks:
      - kong-net
      - backend_frontend

  adapter:
    build: ./adapter
    ports:
      - 4000:80
    depends_on:
      - db
      - influxdb
    networks:
      - kong-net
      - backend_frontend

  db2:
    image: postgres:9.5
    environment:
      POSTGRES_DB: ${KONG_PG_DATABASE:-kong}
      POSTGRES_USER: ${KONG_PG_USER:-kong}
      POSTGRES_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${KONG_PG_USER:-kong}"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
    deploy:
      restart_policy:
        condition: on-failure
    stdin_open: true
    tty: true
    networks:
      - kong-net
      - backend_frontend
    volumes:
      - kong_data:/var/lib/postgresql/data

  kong:
    image: "${KONG_DOCKER_TAG:-kong:latest}"
    user: "${KONG_USER:-kong}"
    depends_on:
      - db2
    environment:
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_CASSANDRA_CONTACT_POINTS: db2
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
      KONG_PG_HOST: db2
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
    secrets:
      - kong_postgres_password
    ports:
      - "8000:8000/tcp"
      - "127.0.0.1:8001:8001/tcp"
      - "8443:8443/tcp"
      - "127.0.0.1:8444:8444/tcp"
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: on-failure
    networks:
      - kong-net
      - backend_frontend
    deploy:
      restart_policy:
        condition: on-failure

  konga:
    image: pantsel/konga:next
    restart: always
    links:
      - kong:kong
    environment:
      KONG_PG_HOST: db2
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      NODE_ENV: production
    depends_on:
      - db2
    networks:
      - kong-net
      - backend_frontend
    ports:
      - "1337:1337"
    secrets:
      - kong_postgres_password

  kong-migration:
    image: kong:latest
    command: "kong migrations bootstrap"
    secrets:
      - kong_postgres_password
    restart: on-failure
    environment:
      KONG_PG_HOST: db2
      KONG_PG_PASSWORD_FILE: /run/secrets/kong_postgres_password
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PG_USER: ${KONG_PG_USER:-kong}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    networks:
      - kong-net
      - backend_frontend
    links:
      - db2
    depends_on:
      - db2

  grafana:
    image: grafana/grafana
    ports:
      - 80:3000
    networks:
      - kong-net
      - backend_frontend
    volumes:
      - ./grafana.db:/var/lib/grafana/grafana.db

volumes:
  mysql_db:
  kong_data:

networks:
  backend_frontend:
  kong-net:

secrets:
  kong_postgres_password:
    file: './secrets/postgres-admin-password.txt'
